#!/bin/sh
width=$1 ; [ 0 = $# ] || shift
delay=$1 ; [ 0 = $# ] || shift
                                                                                                                                                              
if [ -z "$width" ] || [ -z "$delay" ]
then
   clear
   echo " "
   echo "==========================================="
   echo "                 xPovAnim "
   echo "You should give :"
   echo "      - the width of image"
   echo "      - the delay (in msecond)"
   echo "-------------------------------------------"
   echo "Example:"
   echo "       xPovAnim 500 10"
   echo "==========================================="
   echo " "
   exit 1
fi

rm gab?.bmp gab??.bmp
ls gab?.pov gab??.pov | while read i
do
filename=${i%.pov}
echo $filename ...
povray Antialias=on +I$filename.pov +O$filename.bmp +W$width +H$width
done
#convert -delay 10 -loop 1000 gab?.bmp gabedit.gif
convert -delay $delay gab?.bmp gab??.bmp gabedit.gif
echo ' '
echo '=================================='
echo 'gabedit.gif is a gif animated file'
echo '=================================='
