#!/bin/bash

DEFDIR=`pwd`

echo $DEFDIR

# Install wget using port
sudo port install wget

# Install mesa3D OpenGL
sudo port install mesa
sudo port install libGLU

# Install gtk2
sudo port install gtk2

# Install libtool
sudo port install libtool

# Install pkgconfig
sudo port install pkgconfig 

# Install gtkglext
wget https://github.com/allouchear/gabedit/raw/main/MacOS/gtkglext-macport.tar.gz
tar xvf gtkglext-macport.tar.gz
cd gtkglext-macport
./xconfigure
make -j4
sudo make install
cd $DEFDIR


wget https://github.com/allouchear/gabedit/raw/main/MacOS/GabeditSrc252.tar.gz
tar xvf GabeditSrc252.tar.gz
cd GabeditSrc252
cp platforms/CONFIG.MacPorts CONFIG
export PKG_CONFIG_PATH=/opt/local/lib/pkgconfig:$PKG_CONFIG_PATH
make -j4 
sudo cp gabedit /opt/local/bin
echo "============================================================="
echo "Gabedit installed in /opt/local/bin"
cd $DEFDIR

echo "You can remove gtkglext-macport*"
echo "You can remove GabeditSrc252*"
echo "============================================================="

